export const majors = [
{name: 'Agriculture, General'},
{name: 'Agribusiness Operations'},
{name: 'Agricultural Business & Management'},
{name: 'Agricultural Economics'},
{name: 'Agricultural Mechanization'},
{name: 'Agricultural Production'},
{name: 'Agronomy & Crop Science'},
{name: 'Animal Sciences'},
{name: 'Food Sciences & Technology'},
{name: 'Horticulture Operations & Management'},
{name: 'Horticulture Science'},
{name: 'Natural Resources Conservation, General'},
{name: 'Environmental Science'},
{name: 'Forestry'},
{name: 'Natural Resources Management'},
{name: 'Wildlife & Wildlands Management'},
{name: 'Architecture, General'},
{name: 'Architectural Environmental Design'},
{name: 'City/Urban/Regional Planning'},
{name: 'Interior Architecture'},
{name: 'Landscape Architecture'},
{name: 'Asian Area Studies'},
{name: 'European Area Studies'},
{name: 'Latin American Area Studies'},
{name: 'North American Area Studies'},
{name: 'Ethnic & Minority Studies, General'},
{name: 'African American Studies'},
{name: 'American Indian/Native American Studies'},
{name: 'Latino/Chicano Studies'},
{name: 'Women’s Studies'},
{name: 'Liberal Arts & General Studies*'},
{name: 'Library Science'},
{name: 'Multi/Interdisciplinary Studies*'},
{name: 'Art, General'},
{name: 'Art History, Criticism & Conservation'},
{name: 'Fine/Studio Arts'},
{name: 'Cinema/Film'},
{name: 'Cinematography/Film/Vide Production'},
{name: 'Dance'},
{name: 'Design & Visual Communications, General'},
{name: 'Fashion/Apparel Design'},
{name: 'Graphic Design'},
{name: 'Industrial Design'},
{name: 'Interior Design'},
{name: 'Music, General'},
{name: 'Music, Performance'},
{name: 'Music, Theory & Composition'},
{name: 'Photography'},
{name: 'Theatre Arts/Drama'},
{name: 'Accounting'},
{name: 'Accounting Technician'},
{name: 'Business Administration & Management, General'},
{name: 'Hotel/Motel Management'},
{name: 'Human Resources Development/Training'},
{name: 'Human Resources Management'},
{name: 'International Business Management'},
{name: 'Labor/Industrial Relations'},
{name: 'Logistics & Materials Management'},
{name: 'Marketing Management & Research'},
{name: 'Office Supervision & Management'},
{name: 'Operations Management & Supervision'},
{name: 'Organizational Behavior'},
{name: 'Purchasing/Procurement/Contracts Management'},
{name: 'Restaurant/Food Services Management'},
{name: 'Small Business Management/Operations'},
{name: 'Travel/Tourism Management'},
{name: 'Business/Management Quantitative Methods, General'},
{name: 'Actuarial Science*'},
{name: 'Business/Managerial Economics'},
{name: 'Finance, General'},
{name: 'Banking & Financial Support Services'},
{name: 'Financial Planning & Services'},
{name: 'Insurance & Risk Management'},
{name: 'Investments & Securities'},
{name: 'Management Information Systems'},
{name: 'Real Estate'},
{name: 'Sales, Merchandising, & Marketing, General'},
{name: 'Fashion Merchandising'},
{name: 'Tourism & Travel Marketing'},
{name: 'Secretarial Studies & Office Administration'},
{name: 'Communications, General'},
{name: 'Advertising'},
{name: 'Digital Communications/Media'},
{name: 'Journalism, Broadcast'},
{name: 'Journalism, Print'},
{name: 'Mass Communications'},
{name: 'Public Relations & Organizational Communication'},
{name: 'Radio & Television Broadcasting'},
{name: 'Communications Technology, General'},
{name: 'Graphic & Printing Equipment Operation*'},
{name: 'Multimedia/Animation/Special Effects'},
{name: 'Radio & Television Broadcasting Technology*'},
{name: 'Family & Consumer Sciences, General'},
{name: 'Adult Development & Aging/Gerontology'},
{name: 'Child Care Services Management'},
{name: 'Child Development'},
{name: 'Consumer & Family Economics'},
{name: 'Food & Nutrition'},
{name: 'Textile & Apparel'},
{name: 'Parks, Recreation, & Leisure, General'},
{name: 'Exercise Science/Physiology/Kinesiology'},
{name: 'Health & Physical Education/Fitness'},
{name: 'Parks/Rec/Leisure Facilities Management'},
{name: 'Sport & Fitness Administration/Management'},
{name: 'Personal Services, General*'},
{name: 'Cosmetology/Hairstyling*'},
{name: 'Culinary Arts/Chef Training'},
{name: 'Funeral Services & Mortuary Science'},
{name: 'Protective Services, General'},
{name: 'Corrections'},
{name: 'Criminal Justice'},
{name: 'Fire Protection & Safety Technology'},
{name: 'Law Enforcement'},
{name: 'Military Technologies*'},
{name: 'Public Administration & Services, General'},
{name: 'Community Organization & Advocacy'},
{name: 'Public Administration'},
{name: 'Public Affairs & Public Policy Analysis'},
{name: 'Social Work'},
{name: 'Computer & Information Sciences, General'},
{name: 'Computer Networking/Telecommunications'},
{name: 'Computer Science & Programming'},
{name: 'Computer Software & Media Applications'},
{name: 'Computer System Administration'},
{name: 'Data Management Technology'},
{name: 'Information Science'},
{name: 'Webpage Design'},
{name: 'Mathematics, General'},
{name: 'Applied Mathematics'},
{name: 'Statistics'},
{name: 'Counseling & Student Services'},
{name: 'Educational Administration'},
{name: 'Special Education'},
{name: 'Teacher Education, General'},
{name: 'Curriculum & Instruction'},
{name: 'Early Childhood Education'},
{name: 'Elementary Education'},
{name: 'Junior High/Middle School Education'},
{name: 'Postsecondary Education'},
{name: 'Secondary Education'},
{name: 'Teacher Assisting/Aide Education'},
{name: 'Teacher Education, Subject-Specific*'},
{name: 'Agricultural Education'},
{name: 'Art Education'},
{name: 'Business Education'},
{name: 'Career & Technical Education'},
{name: 'English-as-a-Second-Language Education'},
{name: 'English/Language Arts Education'},
{name: 'Foreign Languages Education'},
{name: 'Health Education'},
{name: 'Mathematics Education'},
{name: 'Music Education'},
{name: 'Physical Education & Coaching'},
{name: 'Science Education'},
{name: 'Social Studies/Sciences Education'},
{name: 'Aerospace/Aeronautical Engineering'},
{name: 'Agricultural/Bioengineering'},
{name: 'Architectural Engineering'},
{name: 'Biomedical Engineering'},
{name: 'Chemical Engineering'},
{name: 'Civil Engineering'},
{name: 'Computer Engineering'},
{name: 'Construction Engineering/Management'},
{name: 'Electrical, Electronics & Communications Engineering'},
{name: 'Environmental Health Engineering'},
{name: 'Industrial Engineering'},
{name: 'Mechanical Engineering'},
{name: 'Nuclear Engineering'},
{name: 'Drafting/CAD Technology, General'},
{name: 'Architectural Drafting/CAD Technology'},
{name: 'Mechanical Drafting/CAD Technology'},
{name: 'Engineering Technology, General'},
{name: 'Aeronautical/Aerospace Engineering Technologies'},
{name: 'Architectural Engineering Technology'},
{name: 'Automotive Engineering Technology'},
{name: 'Civil Engineering Technology'},
{name: 'Computer Engineering Technology'},
{name: 'Construction/Building Technology'},
{name: 'Electrical, Electronics Engineering Technologies'},
{name: 'Electromechanical/Biomedical Engineering Technologies'},
{name: 'Environmental Control Technologies'},
{name: 'Industrial Production Technologies'},
{name: 'Mechanical Engineering Technology'},
{name: 'Quality Control & Safety Technologies'},
{name: 'Surveying Technology'},
{name: 'English Language & Literature, General'},
{name: 'American/English Literature'},
{name: 'Creative Writing'},
{name: 'Public Speaking'},
{name: 'Foreign Languages/Literatures, General'},
{name: 'Asian Languages & Literatures'},
{name: 'Classical/Ancient Languages & Literatures'},
{name: 'Comparative Literature'},
{name: 'French Language & Literature'},
{name: 'German Language & Literature'},
{name: 'Linguistics'},
{name: 'Middle Eastern Languages & Literatures'},
{name: 'Spanish Language & Literature'},
{name: 'Health Services Administration,General'},
{name: 'Hospital/Facilities Administration'},
{name: 'Medical Office/Secretarial'},
{name: 'Medical Records'},
{name: 'Medical/Clinical Assisting, General'},
{name: 'Dental Assisting'},
{name: 'Medical Assisting'},
{name: 'Occupational Therapy Assisting'},
{name: 'Physical Therapy Assisting'},
{name: 'Veterinarian Assisting/Technology'},
{name: 'Chiropractic (Pre-Chiropractic)'},
{name: 'Dental Hygiene'},
{name: 'Dentistry (Pre-Dentistry)'},
{name: 'Emergency Medical Technology'},
{name: 'Health-Related Professions & Services, General*'},
{name: 'Athletic Training'},
{name: 'Communication Disorder Services (e.g., Speech Pathology)'},
{name: 'Public Health'},
{name: 'Health/Medical Technology, General'},
{name: 'Medical Laboratory Technology'},
{name: 'Medical Radiologic Technology'},
{name: 'Nuclear Medicine Technology'},
{name: 'Respiratory Therapy Technology'},
{name: 'Surgical Technology'},
{name: 'Medicine (Pre-Medicine)'},
{name: 'Nursing, Practical/Vocational (LPN)'},
{name: 'Nursing, Registered (BS/RN)'},
{name: 'Optometry (Pre-Optometry)'},
{name: 'Osteopathic Medicine'},
{name: 'Pharmacy (Pre-Pharmacy)'},
{name: 'Physician Assisting'},
{name: 'Therapy & Rehabilitation, General'},
{name: 'Alcohol/Drug Abuse Counseling'},
{name: 'Massage Therapy'},
{name: 'Mental Health Counseling'},
{name: 'Occupational Therapy'},
{name: 'Physical Therapy (Pre-Physical Therapy)'},
{name: 'Psychiatric/Mental Health Technician'},
{name: 'Rehabilitation Therapy'},
{name: 'Vocational Rehabilitation Counseling'},
{name: 'Veterinary Medicine (Pre-Veterinarian)'},
{name: 'Philosophy'},
{name: 'Religion'},
{name: 'Theology, General'},
{name: 'Bible/Biblical Studies'},
{name: 'Divinity/Ministry'},
{name: 'Religious Education'},
{name: 'Aviation & Airway Science, General'},
{name: 'Aircraft Piloting & Navigation'},
{name: 'Aviation Management & Operations'},
{name: 'Construction Trades (e.g., carpentry, plumbing, electrical)'},
{name: 'Mechanics & Repairers, General'},
{name: 'Aircraft Mechanics/Technology'},
{name: 'Autobody Repair/Technology'},
{name: 'Automotive Mechanics/Technology'},
{name: 'Avionics Technology'},
{name: 'Diesel Mechanics/Technology'},
{name: 'Electrical/Electronics Equip Installation & Repair'},
{name: 'Heating/Air Cond/Refrig Install/Repair'},
{name: 'Precision Production Trades, General'},
{name: 'Machine Tool Technology'},
{name: 'Welding Technology'},
{name: 'Transportation & Materials Moving (e.g., air, ground, & marine)'},
{name: 'Biology, General'},
{name: 'Biochemistry & Biophysics'},
{name: 'Cell/Cellular Biology'},
{name: 'Ecology'},
{name: 'Genetics'},
{name: 'Marine/Aquatic Biology'},
{name: 'Microbiology & Immunology'},
{name: 'Zoology'},
{name: 'Physical Sciences, General'},
{name: 'Astronomy'},
{name: 'Atmospheric Sciences & Meteorology'},
{name: 'Chemistry'},
{name: 'Geological & Earth Sciences'},
{name: 'Physics'},
{name: 'Legal Studies, General*'},
{name: 'Court Reporting*'},
{name: 'Law (Pre-Law)'},
{name: 'Legal Administrative Assisting/Secretarial*'},
{name: 'Paralegal/Legal Assistant'},
{name: 'Social Sciences, General'},
{name: 'Anthropology'},
{name: 'Criminology'},
{name: 'Economics'},
{name: 'Geography'},
{name: 'History'},
{name: 'International Relations & Affairs'},
{name: 'Political Science & Government'},
{name: 'Psychology, Clinical & Counseling'},
{name: 'Psychology, General'},
{name: 'Sociology'},
{name: 'Urban Studies/Urban Affairs'},
]