export const availableInterests = [
    'Hiking',
    'Surfing',
    'Foodie',
    'Camping',
    'Painting',
    'Drawing',
    'Coding',
    'Skating',
    'Biking',
    'Board games',
    'Traveling',
    'Backpacking',
    'Beach’ing',
    'Golfing',
    'Basketball',
    'Reading (Bookworm)',
    'Video games',
    'Tennis',
    'Soccer',
    'Running',
    'Writing' ,
    'Dancing',
    'Netflix Junkie',
    'Cooking (Chef’ing)',
    'Fishing',
    'Yoga',
    'Bowling',
    'Mini golf',
    'Sunset Watching',
    'Bar hopping',
    'Thrifting',
    'Volunteering', 
    'Shopping',
    'Hammocking',
    'Faith',
    'Music Enthusiast',
    'Tech',
    'Sneakerhead',
    'Stonks',
    'Spikeball',
    'Slacklining' ,
]