name: Continuous Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
      - run: npm i -g firebase-tools
      - run: npm ci
      - run: npx lerna bootstrap
      - run: npx lerna run build
      - run: npx lerna run deploy:cd
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}